# -*- coding: utf-8 -*-
"""TASK-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12mc1EzCkRM6TE5bEvQjXZv7SKTrUt42-
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    if y != 0:
        return x / y
    else:
        return "Error: Division by zero"

def calculator():
    print("Simple Calculator")

    # Input
    try:
        num1 = float(input("Enter the first number: "))
        num2 = float(input("Enter the second number: "))
    except ValueError:
        print("Invalid input. Please enter valid numbers.")
        return

    print("Select operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")

    try:
        choice = int(input("Enter choice (1/2/3/4): "))
    except ValueError:
        print("Invalid input. Please enter a number.")
        return

    # Perform calculation based on user's choice
    if choice == 1:
        result = add(num1, num2)
        operator = "+"
    elif choice == 2:
        result = subtract(num1, num2)
        operator = "-"
    elif choice == 3:
        result = multiply(num1, num2)
        operator = "*"
    elif choice == 4:
        result = divide(num1, num2)
        operator = "/"
    else:
        print("Invalid choice. Please enter a number between 1 and 4.")
        return

    # Display result
    if isinstance(result, float):
        print(f"{num1} {operator} {num2} = {result:.2f}")
    else:
        print(result)

# Run the calculator
calculator()